### ISSUE TITLE
Warn People to use `pip3`?

### ISSUE THREAD

**Issue by theonewolf** [eevee/flax#3]
In the `README.md` you say that if someone already has Python3 and pip installed, they can just run:

```bash
pip install --user git+https://github.com/eevee/flax#egg=flax
```

but I found that insufficient on my Ubuntu 14.04 system which has both Python2 and Python3 installed.

I needed to use `pip3` to install otherwise errors occurred (as expected I guess).

**Comment by eevee** [comment]
It does say:

> Note that you may need to use `pip3` and `python3` above, if Python 3 is not the default Python on your system.

But in light of the PEP recommending that Python 3 just be installed as `python3`, maybe I should just stick the 3's in there.  :)

**Comment by theonewolf** [comment]
Gah, normal user not reading the manual here :laughing:

> If you don't know the Python ecosystem, you can pretty much just do this

I think the preface put my mind too much at ease (although I'm more like intermediate with the Python ecosystem).  I lazily hit ctrl+c then ctrl+v and ran into trouble.

I think if your final note also had a copy-pastable field I would have kept reading.
